### ISSUE TITLE
Replace model magic methods by constants

### ISSUE THREAD

**Issue by OmarBazaraa** [hemoali/CodePortal#29]
We need to replace any magic methods in models by the defined constants in all over the project.

Example:
$user->id;
$user->username;
should be changed to
$user[Constants::FLD_USERS_ID];
$user[Constants::FLD_USERS_USERNAME];

**Comment by OmarBazaraa** [comment]
When we did this? ^_^

**Comment by hemoali** [comment]
We're currently doing 😅

**Comment by OmarBazaraa** [comment]
So why closing it? when we are done isA ^_^
